### ISSUE TITLE
LiveSplit not working

### ISSUE THREAD

**Issue by ThePorter02** [HuthTV/BO2-ZM-Synchronized-Livesplit#2]
I have been unable to get the script to work in LiveSplit. When round 1 starts the timer remains still no matter how long time has passed.

While not having much knowledge in programming (only from school) I have tried playing with the values and came to the conclusion that the program is being hooked up correctly but the values aren't being read correctly. Thus I have been unable to fix the issue by myself. I can still start the timer but even when another round begins, the overlay still shows it as being round 2. Also when i pause the game the timer still continues.

**Comment by HuthTV** [comment]
What version of the game are you using? The current asl script only supports playing the game via the redacted or plutonium clients. Steam will not work

**Comment by HuthTV** [comment]
no response
